CREATE DATABASE IF NOT EXISTS {{DB_NAME}};

USE {{DB_NAME}};

CREATE TABLE IF NOT EXISTS ApiCalls
(
    id            INT AUTO_INCREMENT PRIMARY KEY,
    country       VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);